### ISSUE TITLE
Panic in jet_proto::JetPacket::read_from

### ISSUE THREAD

**Issue by ekse** [Devolutions/devolutions-jet#24]
read_from panics if `size` is smaller than 8.

```rust
        let size = reader.read_u16::<BigEndian>()?;
        let flags = reader.read_u8()?;
        let mask = reader.read_u8()?;
        let mut jet_packet = JetPacket::new(flags, mask);

        let mut payload: Vec<u8> = vec![0; (size - 8) as usize];
```

Backtrace

```
#16 0x55ce761a374b in core::panicking::panic::h623fb6e90dd0e464 /rustc/bc2e84ca0939b73fcf1768209044432f6a15c2e5/src/libcore/panicking.rs:49:4
#17 0x55ce75fb2623 in jet_proto::JetPacket::read_from::haf2cc1abe0a51260 /home/ekse/Devolutions/Wayk/devolutions-jet/jet-proto/src/lib.rs:147:43
#18 0x55ce75fa3ee2 in rust_fuzzer_test_input /home/ekse/Devolutions/Wayk/devolutions-jet/jet-proto/fuzz/fuzz_targets/fuzz_jet.rs:12:19
```

**Comment by ekse** [comment]
This panic is still present in the current version, in the `JetMessage::read_payload` method.

**Comment by awakecoding** [comment]
@ekse is this still present? we've got a user who gets panics in his devolutions-jet container intermittently: https://forum.devolutions.net/topics/33452/few-issues-and-few-questions#138948

I'm wondering if this could be one of the possible causes, triggered by internet scanners reaching the jet relay with bad packets.

**Comment by ekse** [comment]
This one is fixed, we now check that the payload is at least 8 bytes.
https://github.com/Devolutions/devolutions-jet/blob/master/jet-proto/src/lib.rs#L175

I will close this issue. I'm running the fuzzer right now, I'll let you know if it finds anything.
